### ISSUE TITLE
Titles of sub-items to be printed more precisely

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/makepdf#14]
Currently, titles of any ms_items referring to sub-parts of works are printed as the work's main title. 
What should be printed is the content of `<label> `of the corresponding sub-part of the work.

For example:

`<title type="complete" ref="LIT1828Mahale#Moses1"/>` is printed as "Book of Odes (መሓልየ፡ ነቢያት፡), CAe 1828". It should be printed as 
"`First Song of Moses (<foreign xml:lang="gez">ጸሎቱ፡ ለሙሴ፡</foreign>)`" which is the content of `<label>` in the textpart with xml:id "Moses1" in LIT1828Mahale.

It is possible that one visualisation rule might not cover all cases in the catalogue, and that some individual adjustments will still be needed for single manuscripts. But in any case, a visualisation of the  `<label> `of the corresponding sub-part of the work is necessary.

**Comment by PietroLiuzzo** [comment]
The PDF.xql script calls on an API request for titles, so that they are the same as in the website by default. 

So, this can be changed in either or a combination of the following ways

1. for everything in the API script of the BetMasApi.

( https://betamasaheft.eu/api/LIT1828Mahale/Moses1/title
returns from [here](https://github.com/BetaMasaheft/BetMasApi/blob/70de111ed1f2c2edd6cb80d29322a6f54961dc79/local/apiTitles.xqm#L68C13-L68C38) another format, but there is no json variant, needed by the PDF.xql script)

1. the function can be replicated in the PDF.xql script to behave differently, pointing thus to a local function rather than to the API
1. editing the XML to contain the desired title as text only for that specific occurrence.
