### ISSUE TITLE
main content title line

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/makepdf#16]
In analogy to the DS catalogue, each manuscript description should have at the beginning a list of all titles of the main content (central, following the shelfmarks and preceding the main data headline https://github.com/BetaMasaheft/makepdf/issues/13)

**Comment by PietroLiuzzo** [comment]
This seams to be a divergence from the DS catalogue rather than an analogy. The DS catalogue, whose code remained untouched in the current package selected titles without `@xml:lang` which had the effect of returning nothing for the current project where `xml:lang='en'` is used. I have selected this values explicitly.
<img width="227" alt="Schermata 2024-02-08 alle 22 01 30" src="https://github.com/BetaMasaheft/makepdf/assets/508012/8dba96e8-a0b5-4aeb-8375-a19436140b0e">
