### ISSUE TITLE
rendering of altIdentifier

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/makepdf#17]
The layout of the rendering of the content of altIdentifier should follow that of the DS catalogue (central, below the main shelfmark)

**Comment by PietroLiuzzo** [comment]
DS catalogue had a mechanism to match `altIdentifer[@xml:id]` and `altIdentifer[@corresp]` which needed to be removed because the assumption that these two exist in pairs is in this case false.
<img width="788" alt="Schermata 2024-02-08 alle 21 54 19" src="https://github.com/BetaMasaheft/makepdf/assets/508012/8ce5bab4-578a-4b74-a599-df1435c5eff6">
