### ISSUE TITLE
example binding

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/makepdf#7]
Potential example for the meeting: print all binding notes in binding, not just the first one

**Comment by PietroLiuzzo** [comment]
This will need an example file.

**Comment by PietroLiuzzo** [comment]
searching in PDF.xql for 'binding' you will land at this piece of code

````xquery
declare function fo:binding($binding  as element(tei:binding)){
if($binding[descendant::tei:decoNote[@xml:id='b1']]) then
<fo:block space-before="2mm" >
<fo:block font-style="italic" space-after="3mm"  page-break-inside="avoid" page-break-after="avoid">Binding</fo:block>
{fo:tei2fo($binding//tei:decoNote[@xml:id='b1'])}
</fo:block>
else ()
};
````

you will immediately see that, probably because of a previous requirement, only a `decoNote` with `@xml:id='b1'` is selected (so, not necessarily the first).

changing `{fo:tei2fo($binding//tei:decoNote[@xml:id='b1'])}` into 

````xquery
{for $bindingNote in $binding//tei:decoNote return fo:tei2fo($bindingNote)}
```` 
will loop through each decoNote.

Still, the Xquery requires that there is a `descendant::tei:decoNote[@xml:id='b1']`. If this is too strong a condition, you may remove the argument `[@xml:id='b1']` and only check that there are descendant decoNote elements

**Comment by thea-m** [comment]
Thanks a lot!
